### ISSUE TITLE
Update the 'Past Events' page (Frontend)

### ISSUE THREAD

**Issue by alexpereira** [dkapper01/boston-code-and-coffee#16]
Depends on #15 for this task to be complete but some initial work is unblocked.

### Acceptance Criteria

- [x] Create UI cards for event photo albums (See mock)
    - [x] should display the event cover picture
    - [x] should include the event date
- [x] Update Past Events page: list UI meetup event cards in grid view
- [x] Clicking on the event photo album card should take user to the album page
- [x] Create a subpage for event photo album (See mock)
   - [x] The album page should have the event date and title
   - [x] The album page should list event photos in grid view

![Image](https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/assets/3411352/51a3796e-fe5f-4881-8d7e-dfca3b3e352a)

![Image](https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/assets/3411352/5e94361d-a50c-4327-9420-67c158e69c09)

**Comment by detective-sokka** [comment]
Merged changes to main branch. Closing this issue
