### ISSUE TITLE
Add Social Media Buttons

### ISSUE THREAD

**Issue by alexpereira** [dkapper01/boston-code-and-coffee#17]
Design in Figma: https://www.figma.com/file/6ti3DRuiTWDEjgD8aWLVWA/Boston-Code-%26-Coffee?type=design&node-id=725-949&mode=design&t=TB1ZMv5safdQnN6o-4

Acceptance Criteria:
- [ ] On the landing page, there should be a section for social media links at the bottom of the page (See mock)
- [ ] The social media section should include links to:
  - The Boston CC LinkedIn page: https://www.linkedin.com/company/boston-code-and-coffee
  - The Discord server: https://www.codeandcoffee.chat
 - [ ] Remove the original 'Join our Discord' button from the landing page

![Image](https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/assets/3411352/54b8e644-ed00-49f8-8cac-e0046fb97a09)

**Comment by detective-sokka** [comment]
@alexpereira I merged the pr. Should I close this issue?
