### ISSUE TITLE
Update Button Text on Main Page

### ISSUE THREAD

**Issue by alexpereira** [dkapper01/boston-code-and-coffee#37]
The current text displayed on buttons on the main page could be optimized for better clarity and user experience. This issue aims to make these buttons more concise and straightforward, enhancing the overall usability of the main page.

**Proposed Changes:**
We recommend shortening the following button texts:

From: "Features Sign Up"
To: "Features"

From: "Code & Coffee Chapters"
To: "Chapters"

From: "Photos from past events"
To: "Past Events"

**Comment by detective-sokka** [comment]
I will make the changes according to the [updated](https://www.figma.com/file/6ti3DRuiTWDEjgD8aWLVWA/Boston-Code-%26-Coffee?type=design&node-id=0-1&mode=design&t=nG8NyDCW8oEAwEYc-0) Figma design.

**Comment by detective-sokka** [comment]
PR - https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/pull/49
