### ISSUE TITLE
Reorder Main Page Buttons for Improved User Flow

### ISSUE THREAD

**Issue by alexpereira** [dkapper01/boston-code-and-coffee#38]
To enhance the user experience and streamline navigation on the main page, we propose reordering the buttons to create a more intuitive user flow. This issue focuses on rearranging the buttons in a way that aligns with user expectations and makes key sections easily accessible.

**Proposed Changes:**
The suggested button order is as follows:

1. About
2. Chapters
3. Features
4. Organizers
5. Past Events

**Comment by detective-sokka** [comment]
PR - https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/pull/49
