### ISSUE TITLE
Enhancements for Past Events Page

### ISSUE THREAD

**Issue by alexpereira** [dkapper01/boston-code-and-coffee#41]
Enhancements:

**Transparent Dark Shadow/Overlay for Improved Readability:**
The current white text on album cover pictures can be hard to read depending on the image background. Adding a transparent dark shadow/overlay behind the text will enhance the readability of the text, ensuring that it remains legible against various image backgrounds.

**Display Picture Count under Event Date:**
To provide users with more context about each album, we should display the count of pictures within each album beneath the event date. This will give users a quick idea of the volume of pictures in each album.

**Address Missing Most Recent Events:**
Investigate and resolve the issue causing the most recent events to be missing from the page. This is crucial for presenting a comprehensive history of our past events to users.

**Comment by detective-sokka** [comment]
Regarding the issue, I have added the shadow overlay and picture count. This is how it is looking rn. 

<img width="811" alt="Screenshot 2023-08-29 at 6 19 42 PM" src="https://github.com/CodeandCoffeeCommunity/boston-code-and-coffee/assets/12006705/f9bf3b07-4f13-41e9-a251-9d935e8690bb">

The text is still not visible very clearly. Should i change the shadow color to yellow maybe?

Regarding the missing most recent events, the events are being displayed as per the data fetched from the meetup api. So i think the issue might be in the backend or on the meetup's side. 

`[
  {
    id: '294255198',
    title: 'Boston Code and Coffee @ CIC',
    dateTime: '2023-07-15T12:00-04:00',
    image: {
      id: '513746345',
      baseUrl: 'https://secure-content.meetupstatic.com/images/classic-events/'
    },
    photoAlbum: { photoCount: 10 }
  },
  {
    id: '294046123',
    title: 'Create your own Board Game or Video Game',
    dateTime: '2023-07-01T13:00-04:00',
    image: {
      id: '513497721',
      baseUrl: 'https://secure-content.meetupstatic.com/images/classic-events/'
    },
    photoAlbum: { photoCount: 1 }
  },
  {
    id: '293960830',
    title: 'Boston Code and Coffee @ CIC',
    dateTime: '2023-07-01T12:00-04:00',
    image: {
      id: '513374093',
      baseUrl: 'https://secure-content.meetupstatic.com/images/classic-events/'
    },
    photoAlbum: { photoCount: 8 }
  },
  // ...
]`

**Comment by bostoncodeandcoffee** [comment]
Let me see if I can get input from Shirley and Nicole on this

**Comment by detective-sokka** [comment]
I was able to display the latest events by modifying GroupPastEventsFragment to show the first 100 events instead of the last 100.
